apiVersion: v1
kind: Secret
metadata:
  namespace: namespace
  name: nomeDoSecret
type: Opaque
data:
  dbname: ZGJzX2NpdWNhCg==
  dbpassword: dHJsX2FqTENyZXJ1X1A3Zwo=
  dbserver: bHRuX3ByZF9zcWwyMDE3Lm1jdGljLmdvdi5icgo=
  dbusername: dWFwX2NpdWNhCg==
  lang: ZW5fVVMuVVRGLTgK

#Segue regra 'CHAVE: VALOR', valor em BASE64
#
#Para gerar BASE64 de um valor: echo 'valor' | base64
#
#Para decode BASE64 de um valor: echo 'ZGJzX2NpdWNhCg==' | base64 --decode
#
#
